#!/bin/sh /etc/rc.common

START=65

WPANTUND_BIN=/usr/sbin/wpantund
WPANTUND_PID_FILE=/var/run/wpantund.pid

start() 
{
    start-stop-daemon -S -q \
        -p $WPANTUND_PID_FILE -m \
        -b -x $WPANTUND_BIN -- -c /etc/wpantund.conf
    # wait 5 seconds to setup dbus and tunnel interface
    sleep 5
}

stop()
{
    start-stop-daemon -K -q -p $WPANTUND_PID_FILE
    rm $WPANTUND_PID_FILE
}
