#!/bin/sh /etc/rc.common

OTBR_WEB_BIN=/usr/sbin/otbr-web
OTBR_WEB_CONF=/etc/default/otbr-web
OTBR_WEB_PID_FILE=/var/run/otbr-web.pid

if [ -f $OTBR_WEB_CONF ]; then
    . $OTBR_WEB_CONF
fi

start() 
{
    start-stop-daemon -S \
        -p $OTBR_WEB_PID_FILE -m \
        -b -x $OTBR_WEB_BIN -- $OTBR_WEB_OPTS
}

stop()
{
    start-stop-daemon -K -q \
        -p $OTBR_WEB_PID_FILE
    rm $OTBR_WEB_PID_FILE
}
